sets.exported={
    item="Eye Drops",
    item="Echo Drops",
    item="Antidote",
    left_ring="Warp Ring",
    item="Holy Water",
    sub="Aeneas",
    item="Mars Orb",
    item="Rolan. Daifuku",
    item="Toolbag (Shihe)",
    item="Grape Daifuku",
    head={ name="Herculean Helm", augments={'"Mag.Atk.Bns."+10','Attack+6','"Treasure Hunter"+2',}},
    item="Pearlsack",
    item="Prism Powder",
    item="S. Astral Detritus",
    left_ring="Echad Ring",
    feet="Pill. Poulaines +3",
    ammo="Barathrum",
    head="Pill. Bonnet +3",
    body="Pillager's Vest +3",
    legs="Pill. Culottes +3",
    sub="Tauret",
    left_ring="Trizek Ring",
    head="Skulker's Bonnet +1",
    body="Skulker's Vest +1",
    legs="Skulk. Culottes +1",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Crit.hit rate+10',}},
    main="Morgelai",
    left_ring="Dim. Ring (Holla)",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dual Wield"+10','Phys. dmg. taken-10%',}},
    left_ring="Dim. Ring (Dem)",
    item="Antacid",
    feet="Skulk. Poulaines +1",
    item="Remedy",
    sub={ name="Sandung", augments={'Accuracy+50','Crit. hit rate+5%','"Triple Atk."+3',}},
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10','Phys. dmg. taken-10%',}},
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%',}},
    item="Miso Ramen",
    body={ name="Plunderer's Vest +1", augments={'Enhances "Ambush" effect',}},
    hands="Pill. Armlets +1",
    neck={ name="Asn. Gorget +2", augments={'Path: A',}},
    sub={ name="Taming Sari", augments={'STR+10','DEX+10','DMG:+15','"Treasure Hunter"+1',}},
    hands={ name="Plun. Armlets +3", augments={'Enhances "Perfect Dodge" effect',}},
    legs={ name="Plun. Culottes +3", augments={'Enhances "Feint" effect',}},
    sub={ name="Twashtar", augments={'Path: A',}},
    sub={ name="Centovente", augments={'TP Bonus +1000',}},
    item="Sublime Sushi",
    item="Linkshell",
    neck="Erudit. Necklace",
    item="Silent Oil",
    item="SP Gobbie Key",
    feet={ name="Plun. Poulaines +3", augments={'Enhances "Assassin\'s Charge" effect',}},
    head={ name="Plun. Bonnet +3", augments={'Enhances "Aura Steal" effect',}},
    item="Living Key",
    item="P. THF Card",
    item="Shihei",
    item="Silver Voucher",
    item="S. Kindred Crest",
    item="Living Key",
    item="Living Key",
    item="Copper Voucher",
    item="Living Key",
    item="Living Key",
    item="Lustreless Hide",
    hands={ name="Chironic Gloves", augments={'"Mag.Atk.Bns."+27','Accuracy+9 Attack+9','Weapon skill damage +7%','Mag. Acc.+14 "Mag.Atk.Bns."+14',}},
    hands={ name="Herculean Gloves", augments={'INT+4','Crit. hit damage +2%','"Treasure Hunter"+2','Accuracy+6 Attack+6','Mag. Acc.+19 "Mag.Atk.Bns."+19',}},
    ammo="Living Bullet",
    ammo="Chrono Bullet",
    hands={ name="Chironic Gloves", augments={'"Mag.Atk.Bns."+27','MND+10','Mag. Acc.+20 "Mag.Atk.Bns."+20',}},
    item="Trump Card",
}