sets.exported={
    item="Eye Drops",
    item="Echo Drops",
    item="Antidote",
    left_ring="Warp Ring",
    item="Holy Water",
    sub="Aeneas",
    item="Living Key",
    item="Rolan. Daifuku",
    item="Toolbag (Shihe)",
    item="Grape Daifuku",
    item="Living Key",
    item="Pearlsack",
    item="Prism Powder",
    head={ name="Herculean Helm", augments={'"Mag.Atk.Bns."+10','Attack+6','"Treasure Hunter"+2',}},
    left_ring="Echad Ring",
    feet="Pill. Poulaines +3",
    ammo="Barathrum",
    head="Pill. Bonnet +3",
    body="Pillager's Vest +3",
    legs="Pill. Culottes +3",
    sub="Tauret",
    left_ring="Trizek Ring",
    head="Skulker's Bonnet +1",
    body="Skulker's Vest +1",
    legs="Skulk. Culottes +1",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Crit.hit rate+10',}},
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dual Wield"+10','Phys. dmg. taken-10%',}},
    left_ring="Dim. Ring (Holla)",
    feet="Skulk. Poulaines +1",
    left_ring="Dim. Ring (Dem)",
    item="Antacid",
    sub={ name="Sandung", augments={'Accuracy+50','Crit. hit rate+5%','"Triple Atk."+3',}},
    item="Remedy",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10','Phys. dmg. taken-10%',}},
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%',}},
    body={ name="Plunderer's Vest +1", augments={'Enhances "Ambush" effect',}},
    item="Miso Ramen",
    hands="Pill. Armlets +1",
    sub={ name="Taming Sari", augments={'STR+10','DEX+10','DMG:+15','"Treasure Hunter"+1',}},
    item="Living Key",
    hands={ name="Plun. Armlets +3", augments={'Enhances "Perfect Dodge" effect',}},
    legs={ name="Plun. Culottes +3", augments={'Enhances "Feint" effect',}},
    sub={ name="Twashtar", augments={'Path: A',}},
    sub={ name="Centovente", augments={'TP Bonus +1000',}},
    neck="Erudit. Necklace",
    item="Sublime Sushi",
    item="Linkshell",
    feet={ name="Plun. Poulaines +3", augments={'Enhances "Assassin\'s Charge" effect',}},
    item="Silent Oil",
    item="SP Gobbie Key",
    head={ name="Plun. Bonnet +3", augments={'Enhances "Aura Steal" effect',}},
    item="Copper Voucher",
    hands={ name="Chironic Gloves", augments={'Weapon skill damage +4%','Attack+29','Accuracy+8 Attack+8',}},
    item="Mog Pell (Silver)",
    item="Hi-Reraiser",
    item="Silver Voucher",
    hands={ name="Herculean Gloves", augments={'INT+4','Crit. hit damage +2%','"Treasure Hunter"+2','Accuracy+6 Attack+6','Mag. Acc.+19 "Mag.Atk.Bns."+19',}},
    item="Shihei",
    item="S. Kindred Crest",
    item="H. Kindred Crest",
    item="Living Key",
    sub="Darksteel Buckler",
    sub="Darksteel Buckler",
    item="Trump Card",
    item="Gil",
}