sets.exported={
    item="Eye Drops",
    item="Echo Drops",
    item="Antidote",
    left_ring="Warp Ring",
    item="Holy Water",
    head={ name="Herculean Helm", augments={'"Mag.Atk.Bns."+10','Attack+6','"Treasure Hunter"+2',}},
    head="Pill. Bonnet +3",
    item="Rolan. Daifuku",
    main="Karambit",
    item="Grape Daifuku",
    hands={ name="Herculean Gloves", augments={'INT+4','Crit. hit damage +2%','"Treasure Hunter"+2','Accuracy+6 Attack+6','Mag. Acc.+19 "Mag.Atk.Bns."+19',}},
    item="Pearlsack",
    item="Prism Powder",
    item="Sublime Sushi",
    left_ring="Echad Ring",
    body="Pillager's Vest +3",
    legs="Pill. Culottes +3",
    item="Silent Oil",
    head="Skulker's Bonnet +1",
    body="Skulker's Vest +1",
    legs="Skulk. Culottes +1",
    left_ring="Trizek Ring",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Crit.hit rate+10',}},
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dual Wield"+10','Phys. dmg. taken-10%',}},
    sub={ name="Taming Sari", augments={'STR+10','DEX+10','DMG:+15','"Treasure Hunter"+1',}},
    sub={ name="Twashtar", augments={'Path: A',}},
    hands="Pill. Armlets +1",
    left_ring="Dim. Ring (Holla)",
    sub="Aeneas",
    left_ring="Dim. Ring (Dem)",
    item="Antacid",
    sub={ name="Centovente", augments={'TP Bonus +1000',}},
    item="Remedy",
    feet="Pill. Poulaines +3",
    neck="Erudit. Necklace",
    sub={ name="Ternion Dagger +1", augments={'Path: A',}},
    head={ name="Plun. Bonnet +3", augments={'Enhances "Aura Steal" effect',}},
    body={ name="Plunderer's Vest +3", augments={'Enhances "Ambush" effect',}},
    feet="Skulk. Poulaines +1",
    sub={ name="Sandung", augments={'Accuracy+50','Crit. hit rate+5%','"Triple Atk."+3',}},
    neck={ name="Asn. Gorget +2", augments={'Path: A',}},
    item="Toolbag (Shihe)",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10','Phys. dmg. taken-10%',}},
    feet={ name="Plun. Poulaines +3", augments={'Enhances "Assassin\'s Charge" effect',}},
    legs={ name="Plun. Culottes +3", augments={'Enhances "Feint" effect',}},
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%',}},
    item="Linkshell",
    item="Living Key",
    item="Living Key",
    item="Shikanofuda",
    item="Inoshishinofuda",
    item="Chonofuda",
    item="Shihei",
    item="S. Kindred Crest",
    item="H. Kindred Crest",
    item="Copper Voucher",
    item="S. Astral Detritus",
    item="P. THF Card",
    feet="Flam. Gambieras +2",
    hands={ name="Plun. Armlets +3", augments={'Enhances "Perfect Dodge" effect',}},
    legs={ name="Herculean Trousers", augments={'"Mag.Atk.Bns."+27','Accuracy+27','Mag. Acc.+17 "Mag.Atk.Bns."+17',}},
    item="Living Key",
    item="Living Key",
    item="Lustreless Hide",
    item="Kin's Scale",
    item="Tavnazian Taco",
    sub="Tauret",
    ammo="Barathrum",
    item="Gil",
}