
    send_command('bind #insert input //send @others //gs c cycleback Element')
    send_command('bind #delete input //send @others //gs c cycle Element')
    send_command('bind #[ input //send @others //gs c toggle MagicBurst')
    send_command('bind #] input //send @others //gs c toggle Auto')

    send_command('bind #` input //send @others //gs c cycle SongMode')

    send_command('bind #1 input //send @others /so "Honor March" <me>')
    send_command('bind #2 input //send @others /so "Victory March" <me>')
    send_command('bind #3 input //send @others /so "Valor Minuet V" <me>')
    send_command('bind #4 input //send @others /so "Blade Madrigal" <me>')
    send_command('bind #5 input //send @others //gs c carol')
    send_command('bind #6 input //send @others /so "Pining Nocturne" <t>')
    send_command('bind #7 input //send @others /ma "Dia II" <t>')
    send_command('bind #8 input //send @others /so "Horde Lullaby" <t>')
    send_command('bind #9 input //send @others /so "Carnage Elegy" <t>')
    send_command('bind #0 input //send @others /so "Magic Finale" <t>')

    send_command('bind #e input //send @others /ma "Haste" <t>')
    send_command('bind #r input //send @others /ma "Refresh" <t>')
    send_command('bind #t input //send @others /ma "Blink" <me>')
    send_command('bind #y input //send @others /ma "Phalanx" <me>')
    send_command('bind #u input //send @others /ma "Stoneskin" <me>')
    send_command('bind #i input //send @others /ma "Aquaveil" <me>')
    send_command('bind #o input //send @others /ma "Cure IV" <t>')
    send_command('bind #p input //send @others /ja "Pianissimo" <me>')

    send_command('bind #numpad7 input //send @others /ma "Paralyna" <t>')
    send_command('bind #numpad8 input //send @others /ma "Silena" <t>')
    send_command('bind #numpad9 input //send @others /ma "Blindna" <t>')
    send_command('bind #numpad4 input //send @others /ma "Poisona" <t>')
    send_command('bind #numpad5 input //send @others /ma "Stona" <t>')
    send_command('bind #numpad6 input //send @others /ma "Viruna" <t>')
    send_command('bind #numpad1 input //send @others /ma "Cursna" <t>')
    send_command('bind #numpad+ input //send @others /ma "Erase" <t>')
