    -- Dual Box Key Binds (Requires Send and Shortcuts)
    send_command('bind #f1 input //send safiyeh /ta <p0>')
    send_command('bind #f2 input //send safiyeh /ta <p1>')
    send_command('bind #f3 input //send safiyeh /ta <p2>')
    send_command('bind #f4 input //send safiyeh /ta <p3>')
    send_command('bind #f5 input //send safiyeh /ta <p4>')
    send_command('bind #f6 input //send safiyeh /ta <p5>')
    send_command('bind #f7 input //send safiyeh /ta Arislan; wait1; input //send safiyeh /follow <t>')
    send_command('bind #f8 input //send safiyeh /ta <bt>')

    send_command('bind #f9 input //send safiyeh //gs c cycle offensemode')
    send_command('bind #f10 input //send safiyeh //gs c cycle defensemode')
    send_command('bind #f11 input //send safiyeh //gs c cycle castingmode')
    send_command('bind #f12 input //send safiyeh //gs c cycle idlemode')

    send_command('bind #` input //send safiyeh /ja "Afflatus Solace" <me>')

    send_command('bind #1 input //send safiyeh /ma "Cure III" <t>')
    send_command('bind #2 input //send safiyeh /ma "Cure IV" <t>')
    send_command('bind #3 input //send safiyeh /ma "Cure V" <t>')
    send_command('bind #4 input //send safiyeh /ma "Curaga II" <t>')
    send_command('bind #5 input //send safiyeh /ma "Curaga III" <t>')
    send_command('bind #6 input //send safiyeh /ma "Aurorastorm" <me>')

    send_command('bind #7 input //send safiyeh /ma "Dia II" <t>')
    send_command('bind #8 input //send safiyeh /ma "Silence" <t>')
    send_command('bind #9 input //send safiyeh /ma "Paralyze" <t>')
    send_command('bind #0 input //send safiyeh /ma "Dispel" <t>')

    send_command('bind #q input //send safiyeh /ma "Light Arts" <me>')
    send_command('bind #e input //send safiyeh /ma "Haste" <t>')
    send_command('bind #r input //send safiyeh /ma "Refresh" <t>')
    send_command('bind #t input //send safiyeh /ma "Blink" <me>')
    send_command('bind #y input //send safiyeh /ma "Phalanx" <me>')
    send_command('bind #u input //send safiyeh /ma "Stoneskin" <me>')
    send_command('bind #i input //send safiyeh /ma "Aquaveil" <me>')
    send_command('bind #o input //send safiyeh /ma "Regen IV" <t>')
    send_command('bind #p input //send safiyeh /ja "Sublimation" <me>')

    send_command('bind #, input //send safiyeh /ma "Sneak" <t>')
    send_command('bind #. input //send safiyeh /ma "Invisible <t>')
    send_command('bind #[ input //send safiyeh /ja "Accession" <me>')
    send_command('bind #] input //send safiyeh /ja "Divine Caress" <me>')

    send_command('bind #- input //send safiyeh /follow <t>')

    send_command('bind #numpad7 input //send safiyeh /ma "Paralyna" <t>')
    send_command('bind #numpad8 input //send safiyeh /ma "Silena" <t>')
    send_command('bind #numpad9 input //send safiyeh /ma "Blindna" <t>')
    send_command('bind #numpad4 input //send safiyeh /ma "Poisona" <t>')
    send_command('bind #numpad5 input //send safiyeh /ma "Stona" <t>')
    send_command('bind #numpad6 input //send safiyeh /ma "Viruna" <t>')
    send_command('bind #numpad1 input //send safiyeh /ma "Cursna" <t>')
    send_command('bind #numpad+ input //send safiyeh /ma "Erase" <t>')
    send_command('bind #numpad. input //send safiyeh /ma "Esuna" <me>')
