
    send_command('bind #insert input //send @others //gs c cycleback Element')
    send_command('bind #delete input //send @others //gs c cycle Element')
    send_command('bind #[ input //send @others //gs c toggle MagicBurst')
    send_command('bind #] input //send @others //gs c toggle Auto')

    send_command('bind #` input //send @others /ja "Full Circle" <me>')

    send_command('bind #1 input //send @others /ma "Geo-Frailty" <t>')
    send_command('bind #2 input //send @others /ma "Indi-Fury" <t>')
    send_command('bind #3 input //send @others /ma "Indi-Haste <t>')
    send_command('bind #4 input //send @others /ma "Indi-Refresh" <t>')
    send_command('bind #5 input //send @others /ma "Geo-Malaise" <t>')
    send_command('bind #6 input //send @others /ma "Indi-Acumen" <t>')

    send_command('bind #7 input //send @others /ma "Dia II" <t>')
    send_command('bind #8 input //send @others /ma "Silence" <t>')
    send_command('bind #9 input //send @others /ma "Paralyze" <t>')
    send_command('bind #0 input //send @others /ma "Cure" <p1>')
    --send_command('bind #7 input //send @others /ma "Dispelga" <t>')
    --send_command('bind #8 input //send @others /ma "Sleepga" <t>')
    --send_command('bind #0 input //send @others /ma "Stun" <t>')

    send_command('bind #q input //send @others //gs c nuke')
    send_command('bind #w input //send @others /ma "Aspir III" <t>')
    send_command('bind #e input //send @others /ma "Haste"" <t>')
    send_command('bind #r input //send @others /ma "Refresh" <t>')
    send_command('bind #t input //send @others /ma "Blink" <me>')
    send_command('bind #y input //send @others /ma "Phalanx" <me>')
    send_command('bind #u input //send @others /ma "Stoneskin" <me>')
    send_command('bind #i input //send @others /ma "Aquaveil" <me>')
    send_command('bind #o input //send @others /ma "Cure IV" <t>')
    send_command('bind #p input //send @others /ja "Entrust" <me>')

    send_command('bind #, input //send @others /ma "Sneak" <t>')
    send_command('bind #. input //send @others /ma "Invisible <t>')
    send_command('bind #a input //send @others /ja "Ecliptic Attrition" <me>')
    send_command('bind #s input //send @others /ja "Lasting Emanation" <me>')
    send_command('bind #d input //send @others /ja "Dematerialize" <me>')
    send_command('bind #v input //send @others /ja "Life Cycle" <me>')
    send_command('bind #b input //send @others /ja "Blaze of Glory" <me>')
    send_command('bind #n input //send @others /ja "Radial Arcana" <me>')

    send_command('bind #numpad7 input //send @others /ma "Paralyna" <t>')
    send_command('bind #numpad8 input //send @others /ma "Silena" <t>')
    send_command('bind #numpad9 input //send @others /ma "Blindna" <t>')
    send_command('bind #numpad4 input //send @others /ma "Poisona" <t>')
    send_command('bind #numpad5 input //send @others /ma "Stona" <t>')
    send_command('bind #numpad6 input //send @others /ma "Viruna" <t>')
    send_command('bind #numpad1 input //send @others /ma "Cursna" <t>')
    send_command('bind #numpad2 input //send @others /ma "Cursna" Gary')
    send_command('bind #numpad+ input //send @others /ma "Erase" <t>')
    send_command('bind #numpad0 input //send @others /ma "Sacrifice" <t>')
    send_command('bind #numpad. input //send @others /ma "Esuna" <me>')
