    send_command('bind #` input //send @others /ja "Afflatus Solace" <me>')

    send_command('bind #1 input //send @others /ma "Cure III" <t>')
    send_command('bind #2 input //send @others /ma "Cure IV" <t>')
    send_command('bind #3 input //send @others /ma "Cure V" <t>')
    send_command('bind #4 input //send @others /ma "Curaga II" <t>')
    send_command('bind #5 input //send @others /ma "Curaga III" <t>')
    send_command('bind #6 input //send @others /ma "Aurorastorm" <me>')

    send_command('bind #7 input //send @others /ma "Dia II" <t>')
    send_command('bind #8 input //send @others /ma "Silence" <t>')
    send_command('bind #9 input //send @others /ma "Paralyze" <t>')
    send_command('bind #0 input //send @others /ma "Dispel" <t>')

    send_command('bind #q input //send @others /ma "Light Arts" <me>')
    send_command('bind #w input //send @others /ma "Aspir" <t>')
    send_command('bind #e input //send @others /ma "Haste" <t>')
    send_command('bind #r input //send @others /ma "Refresh" <t>')
    send_command('bind #t input //send @others /ma "Blink" <me>')
    send_command('bind #y input //send @others /ma "Phalanx" <me>')
    send_command('bind #u input //send @others /ma "Stoneskin" <me>')
    send_command('bind #i input //send @others /ma "Aquaveil" <me>')
    send_command('bind #o input //send @others /ma "Regen IV" <t>')
    send_command('bind #p input //send @others /ja "Sublimation" <me>')

    send_command('bind #, input //send @others /ma "Sneak" <t>')
    send_command('bind #. input //send @others /ma "Invisible <t>')
    send_command('bind #[ input //send @others /ja "Accession" <me>')
    send_command('bind #] input //send @others /ja "Divine Caress" <me>')

    send_command('bind #numpad7 input //send @others /ma "Paralyna" <t>')
    send_command('bind #numpad8 input //send @others /ma "Silena" <t>')
    send_command('bind #numpad9 input //send @others /ma "Blindna" <t>')
    send_command('bind #numpad4 input //send @others /ma "Poisona" <t>')
    send_command('bind #numpad5 input //send @others /ma "Stona" <t>')
    send_command('bind #numpad6 input //send @others /ma "Viruna" <t>')
    send_command('bind #numpad1 input //send @others /ma "Cursna" <t>')
    send_command('bind #numpad2 input //send @others /ma "Cursna" Gary')
    send_command('bind #numpad+ input //send @others /ma "Erase" <t>')
    send_command('bind #numpad0 input //send @others /ma "Sacrifice" <t>')
    send_command('bind #numpad. input //send @others /ma "Esuna" <me>')
